version: "3"
services:
  node-app:
    build:
      context: .
      target: development

      args:
        - NODE_ENV=production

    environment:
      - NODE_ENV=production

    command: npm start
