version: "3"
services:
  node-app:
    build:
      context: .
      target: development

    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/myFolder/src:ro

    command: npm run start-dev
